title: gd studios
email: buttface@jackf.me
description: >
  An international directory of graphic design agencies/studios/consultancies/firms.
url: https://studios.silly.graphics
timezone: Etc/UTC

markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package*
  - README.md
  - Gemfile
  - LICENSE.txt
  - .gitignore
  - graphics

assets:
  # digest: true
  # cache: false
  sources:
    - "_assets/css"
    - "_assets/js"
